### ISSUE TITLE
merge latest changes of Template/layout.php 

### ISSUE THREAD

**Issue by BlueTeck** [creecros/Customizer#100]
Hi @creecros ,

the changes of  https://github.com/kanboard/kanboard/commit/e65045f9341361cde730fce14b0b7e273eae7f15 have to be applied to this plugin. Otherwise the the Gantt Plugin isn't working anymore.

https://github.com/creecros/Customizer/blob/master/Template/layout/layout.php

Regards,
Timo

**Comment by creecros** [comment]
make PR? or me do it?

**Comment by BlueTeck** [comment]
I've created #101

**Comment by creecros** [comment]
Wondering if it will be backwards compatible, have you tested in old KB versions?

**Comment by BlueTeck** [comment]
@creecros now it should be

**Comment by creecros** [comment]
@BlueTeck thanks! That helps out so much! I'll make a new release asap.

**Comment by orware** [comment]
Just wanted to send a ping on this one to see if the PR could be merged along with a new release so we can update things here on our end to fix that issue I noticed in #103?

Thank you!

**Comment by creecros** [comment]
Thanks for reminder. I'm very busy these days!

**Comment by creecros** [comment]
Sent to guys collab invites so you don't have to wait for me @BlueTeck @orware

**Comment by orware** [comment]
@creecros I created a new release after merging the PR (I wasn't sure exactly how you handled the named release ZIP file, but I downloaded the source code and then renamed the folder inside the ZIP to just "Customizer" and then added it to the release. Hopefully that's basically the same procedure you normally follow.

I checked my Kanboard install to see if it registered there being a new update right away but it seemed to not be showing yet, but perhaps that takes a few minutes before it knows an update has been released. I'll try again a little later today and see if the update goes through successfully (even though looking at the PR, it's a pretty minor change that I could apply manually).

**Comment by creecros** [comment]
You register new releases here:
https://github.com/kanboard/website

Check out previous PRs to understand how.

Or, I'll get to it, maybe tonight.

**Comment by orware** [comment]
@creecros Thanks for the pointer...I've updated the plugins.json file with the new version and submitted a PR for that (I didn't see anything in the plugins.html file that needed updating in this case, but could be wrong).

**Comment by creecros** [comment]
Just the json. The html would be for changing the description.
