### ISSUE TITLE
Getting these errors when I got to the customizer settings page

### ISSUE THREAD

**Issue by faspina** [creecros/Customizer#102]
Version info:

    Application version: 1.2.13
    PHP version: 7.3.0
    PHP SAPI: apache2handler
    HTTP Client: cURL
    OS version: Linux 4.19.88-Unraid
    Database driver: mysql
    Database version: 10.4.11-MariaDB-1:10.4.11+maria~bionic-log
    Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:71.0) Gecko/20100101 Firefox/71.0

Getting these errors in the customizer screen:
Warning: filemtime(): stat failed for plugins/Customizer/Assets/rgbaColorPicker/rgbaColorPicker.css in /srv/http/kanboard/app/Helper/AssetHelper.php on line 37

Warning: filemtime(): stat failed for plugins/Customizer/Assets/css/customizer.css in /srv/http/kanboard/app/Helper/AssetHelper.php on line 37

Warning: filemtime(): stat failed for plugins/KanboardCSS/kanboardcss.css in /srv/http/kanboard/app/Helper/AssetHelper.php on line 37

Warning: filemtime(): stat failed for plugins/Customizer/Assets/css/theme.css in /srv/http/kanboard/app/Helper/AssetHelper.php on line 37

Warning: filemtime(): stat failed for plugins/Customizer/Assets/rgbaColorPicker/rgbaColorPicker.js in /srv/http/kanboard/app/Helper/AssetHelper.php on line 24

Warning: filemtime(): stat failed for plugins/Customizer/Assets/js/customizer.js in /srv/http/kanboard/app/Helper/AssetHelper.php on line 24

**Comment by creecros** [comment]
I'll run tests next chance I get, haven't tested with 1.2.13 yet. I'll let you know what I find.

**Comment by bwdymods** [comment]
I had the same problem using a nonstandard plugins directory. Had to manually edit the paths to those files to reflect the change.

**Comment by creecros** [comment]
I'm not having any issues, but the above post would make sense, anything non standard could potentially cause an issue of this nature. Make sure your config.php for kanboard is setup correctly defining your plugin folder.

**Comment by bwdymods** [comment]
the path was hardcoded and did not reference config in a couple places (example: https://github.com/creecros/Customizer/blob/master/Plugin.php#L25 ), which are the ones throwing those errors. I edited the hardcoded path to reflect my changes and the problem went away. (perhaps they should be checking config?)

**Comment by creecros** [comment]
That's not a hardcode. Simply change your plugin path in keyboards config. However, being in the data folder, might cause permission issues.
