### ISSUE TITLE
Experiencing Similar Issue Fixed in Kanboard

### ISSUE THREAD

**Issue by orware** [creecros/Customizer#103]
I'm experiencing this issue on my end right now:
https://github.com/kanboard/kanboard/issues/4335

However, it's with the English language and I do have Customizer in use.

I'm reporting the problem here since I made a local copy of my site to test further and started by taking out all of the plugins I had installed.

After doing so, the issue went away.

I then started by adding just Customizer back in (lucky guess) and the issue returned.

I'm not sure if it's something that's been saved in Customizer (cached perhaps?) or if it is actually something that's out of date in Customizer that needs updating but I'm going to try and take a closer look later today to figure it out if I can.

If I come up with a solution I'll share it back here, but if you have any ideas of what could be causing the issue that would be appreciated as well!

**Comment by BlueTeck** [comment]
see #100

**Comment by orware** [comment]
@BlueTeck I just merged that PR, so I'll see if I can also create a new minor release based on the access @creecros has provided.
