### ISSUE TITLE
Plugin version not updated

### ISSUE THREAD

**Issue by kenlog** [creecros/Customizer#104]
Hi @orware I report the version number for the latest release v1.13.2 is not updated. This causes problems for the correct update of the plug-in in kanboard. I recommend that you update the version and release again. Thanks for the contribution! :+1: 

https://github.com/creecros/Customizer/blob/aa4b2e00f34081c6daf86731453fea64846abbd4/Plugin.php#L160

**Comment by orware** [comment]
Thanks @kenlog for pointing that out. I've incremented things to 1.13.3 since I botched that 1.13.2 release by forgetting about that.

**Comment by creecros** [comment]
Thanks guys 👍
