### ISSUE TITLE
KindaDark theme prevents subtask status icons from showing up

### ISSUE THREAD

**Issue by nekohayo** [creecros/Customizer#105]
Apparently the "KindaDark" theme is a fork of https://github.com/kenlog/Oxygen to be compatible with Customizer, I presume?

It looks great, except there's one bug that is kind of a showstopper in the "KindaDark" version: you can't see the clickable checkbox/gear icons for subtasks...

**Comment by nekohayo** [comment]
This seems to be caused by line 69 in KindaDark.css:
```
a .fa {
	color: #fff;
}
```

I was able to work around it for now with a custom CSS rule like this, but I'm suspecting that my workaround CSS is quite stupid:

```
.js-subtask-toggle-status i {
	color: black !important;
}
```

**Comment by nekohayo** [comment]
Also there are other similar issues in the theme, such as the icons for swimlanes and for compact cards in the board view, which means my workaround CSS becomes something like this (no idea what I'm doing, just trial and error):

```
.js-subtask-toggle-status i,
.task-board-collapsed a.js-modal-large i.fa,
a.board-swimlane-toggle i.fa {
	color: black !important;
}
```

**Comment by creecros** [comment]
i think i got it with commit 3db909bfb9cce9025b063d31a80923e34dbbf163
