### ISSUE TITLE
Header Logo size doesn't change

### ISSUE THREAD

**Issue by MushMello** [creecros/Customizer#106]
I can change the size of every logo, except the header one. It always stays at height=50px and makes the header bar unnecessarily tall.  The logo image is just 57*38px big, but even if I would choose 250 on the slider, it would still be just 50 px tall. We changed some things, but that's not the reason, cause a complete reinstall didn't work either

**Comment by creecros** [comment]
Sounds like your cache.

**Comment by MushMello** [comment]
Refreshed it, but that didn't work. Also noone of us can resize that specific icon with the slider, while the others still do their job

**Comment by creecros** [comment]
A refresh doesn't clear your cache. Either way, you lack detail required to problem solve an issue. 8.6k downloads, and you are the only one with said issue, so there needs to be more information as to what is different about your install versus the 8.6k other downloaded installs. Also, make sure your JS is enabled in your browser.

**Comment by creecros** [comment]
closing until new information is added.
