### ISSUE TITLE
Errors on non standard plugins folder

### ISSUE THREAD

**Issue by Ronaldvr** [creecros/Customizer#107]
Can it be that for some reason the plugins directory is hardcoded? I run the docker version of kanboard, and I copied the default config.php. This had sort of an error in that 

`define('DATA_DIR', __DIR__.DIRECTORY_SEPARATOR.'data');`

resulted (together with another setting in the yml) dat the data dir became  /data/data and plugins dir /data/plugins . But I would assume that a plugin reads that specific variable to get the correct path this does not seem to be the case for Customizer and I get errors as:

Warning: filemtime(): stat failed for plugins/WeKanboard/WeKanboard.css in /var/www/app/app/Helper/AssetHelper.php on line 37

Warning: filemtime(): stat failed for plugins/Customizer/Assets/rgbaColorPicker/rgbaColorPicker.css in /var/www/app/app/Helper/AssetHelper.php on line 37

**Comment by creecros** [comment]
I too run the docker kanboard.

You're errors are not specific to customizer, there is another plugin listed with same error.

**Comment by creecros** [comment]
If you give me enough info on how to replicate what you did, I can look into it. Otherwise, not much I can do to help.

**Comment by Ronaldvr** [comment]
Hello,

I run it with a custom config.php, an din the meantime I solved it by adding:

`define('REALDIR', str_split(__DIR__, strrpos(__DIR__,'/'))[0]);`

and changing 
`define('PLUGINS_DIR', DATADIR.DIRECTORY_SEPARATOR.'plugins');`

to
`define('PLUGINS_DIR', REALDIR.DIRECTORY_SEPARATOR.'plugins');`

(It seems `__DIR__`  refers actually to `DATADIR`).

However, you use for instance

`'plugins/Customizer/Assets/css/theme.css' `

where you probably should use

`PLUGINDIR.DIRECTORY_SEPARATOR.'Customizer/Assets/css/theme.css'`

?

**Comment by creecros** [comment]
You are welcome to a make a PR if you feel this improves the plugin.
