### ISSUE TITLE
<code> color and background color?

### ISSUE THREAD

**Issue by BlueTeck** [creecros/Customizer#108]
Hi @creecros,

in the customizer css, the tag ```<code>``` is styled, which leads to a "ugly" rendering of source code in markdown:

with customizer css:
![image](https://user-images.githubusercontent.com/1961634/78548465-22101080-7801-11ea-97a9-f1e313e69f73.png)

without customizer code css:
![image](https://user-images.githubusercontent.com/1961634/78548537-3d7b1b80-7801-11ea-9af9-a609a8428630.png)

Could this css be removed oder prefixed with a class?
https://github.com/creecros/Customizer/blob/752d4378afb95ec14ec13d1deb47df4eadc86cec/Assets/css/customizer.css#L16-L25

Regards,
Timo

**Comment by creecros** [comment]
@BlueTeck 
I am really not a css guy, I think @kenlog might know. I truly have no idea.

**Comment by kenlog** [comment]
Hi @BlueTeck and @creecros to remove the background color you need to delete the following line
https://github.com/creecros/Customizer/blob/752d4378afb95ec14ec13d1deb47df4eadc86cec/Assets/css/customizer.css#L19

**Comment by BlueTeck** [comment]
Of course, but the question is, why is it there?

**Comment by kenlog** [comment]
I didn't add it, this can help @BlueTeck 
https://github.com/creecros/Customizer/blame/752d4378afb95ec14ec13d1deb47df4eadc86cec/Assets/css/customizer.css#L19

**Comment by creecros** [comment]
i have no issues if it is removed. maybe it should be a preference, i don't know.
