### ISSUE TITLE
Was there at one point a 1.13.5 release?

### ISSUE THREAD

**Issue by mike-syseng** [creecros/Customizer#110]
I installed Customizer via the Kanboard plugin directory, not through the CLI, back around January/February. My Kanboard states that version 1.13.5 of Customizer is installed, but the latest release on here is 1.13.4. When upgrading plugins via the CLI, it says it's up-to-date, and doesn't get 1.13.4, which has a more recent release date. Was there at one point a 1.13.5 version that's since been removed?

Thanks, I really appreciate this plugin!

**Comment by creecros** [comment]
1.13.5 is the masters current version, you would have had to install using the master to get that version. The latest official release is 1.13.4.
