### ISSUE TITLE
[Feature request] [Help] Change task background color on task board

### ISSUE THREAD

**Issue by kentone** [creecros/Customizer#111]
Hello,

Im currently implementing Kanboard on my company, my users requested me if I could make the task background colored on the Galaxy theme.

I tried my best to find a way on the css, but I have not been able :(

Could you help me with this? Also this option would be nice to have on the customizer! (Solid color task background)

Thanks for your amazing job,

Cheers!

**Comment by creecros** [comment]
Not sure i understand what you're asking for

**Comment by creecros** [comment]
Still don't understand what you are asking for, so closing for now.
