### ISSUE TITLE
Create userthemes error?

### ISSUE THREAD

**Issue by tatatafuku** [creecros/Customizer#112]
Hello

I tried to create a user theme from "theme creator".

After creating it, I used it from "Manage themes", but "Warnning" was displayed.

`Warning: filemtime(): stat failed for plugins/Customizer/Assets/css/userthemes/test.css in /var/www/html/kanboard/app/Helper/AssetHelper.php on line 37`

And that was not reflected.

Also, the user theme did not exist in the "plugins/Customizer/Assets/css/userthemes/" directory.

Is there any solution?

Thanks a lot

Best regards

**Comment by creecros** [comment]
Most likely, permission issues. Try manually creating the folder plugins/Customizer/Assets/css/userthemes
And see if that works

**Comment by tatatafuku** [comment]
As you said, it was a permission issue.
It was solved by making the following changes.

Thank you so, so much!

```
[before]
drwxr-xr-x 2 root root ... **userthemes**

[after]
drwxrwxrwx 2 root root ... **userthemes**
```

**Comment by creecros** [comment]
👍
