### ISSUE TITLE
Blueboard and Material missing web-notification-icon class

### ISSUE THREAD

**Issue by thinkingBanana** [creecros/Customizer#113]
Blueboard.css and Material.css is missing the web-notification-icon class, resulting no visual indication when new notification comes in.

**Comment by creecros** [comment]
No PR?

**Comment by thinkingBanana** [comment]
Didn't know how to create one, just learned! #114

**Comment by creecros** [comment]
So its just Blueboard? I'll merge next chance I get.

**Comment by thinkingBanana** [comment]
Yeah, upon further testing, I only discovered this issue in Blueboard.
