### ISSUE TITLE
js error on last version

### ISSUE THREAD

**Issue by micker** [creecros/Customizer#118]
hello style arn't render .. because
```
Uncaught TypeError: Cannot set property 'oninput' of null
    at customizer.js?1554814238:55
```
did you have an idea ?
regards

**Comment by creecros** [comment]
Thats pretty vague, and the js hasn't changed in over a year.

**Comment by micker** [comment]
the style is broke bakend render ... what did you need ?

**Comment by creecros** [comment]
Just tell me what you're doing to get the issue, so I can replicate

**Comment by micker** [comment]
i just change someting in customizer ...

**Comment by creecros** [comment]
again, pretty vague, I just tested in the customizer panel, changed every value and no errors occurred. If I can't replicate it, I can't fix it.

**Comment by creecros** [comment]
also, which version? 1.13.4?

**Comment by micker** [comment]
![image](https://user-images.githubusercontent.com/2539440/94589317-6d255080-0285-11eb-8db1-7cdef0ad75bf.png)
kanboard 1.2.15
customizer 1.9.1

**Comment by creecros** [comment]
Ok. Well, that's not the latest version, by any stretch of the imagination. You are like 13 releases behind. Upgrade and try again.

**Comment by micker** [comment]
strange kanboard say that is outdate how i can update manualy ?

**Comment by micker** [comment]
sorry myfault i didn't copy the good version

1.13.4
--
![image](https://user-images.githubusercontent.com/2539440/94591778-d0fd4880-0288-11eb-9a62-44a7e6721fc2.png)

**Comment by micker** [comment]
Please reopen it :wink:

**Comment by creecros** [comment]
I still can't reproduce the error. So, if there is no new info, not sure what I can do

**Comment by micker** [comment]
i can open an acces for you ?

**Comment by creecros** [comment]
Also, did you have to upgrade, or did you just copy  the wrong version number. It would make sense for it to occur in v1.9.1, it makes no sense to occur in 1.13.4

**Comment by creecros** [comment]
> i can open an acces for you ?

Sure

**Comment by micker** [comment]
an email ?

**Comment by creecros** [comment]
creecros@gmail.com

**Comment by creecros** [comment]
no, you are still using 1.9.1
![image](https://user-images.githubusercontent.com/26339368/94602203-8d8fe380-0262-11eb-8fc3-5b0c4161676e.png)

upgrade, and im 99% positive the error will go away

**Comment by creecros** [comment]
i do see that in you installer, it shows as up to date, but it is not, so its possible, all you need to do is reboot your machine. not sure how your server is setup, or whats going on there.

**Comment by micker** [comment]
hello i remove folder and re upload it seem good but already says 1.9.1 without update ... strange not ?

**Comment by creecros** [comment]
it is strange, but your server may be caching the files, which is why i said reboot.

**Comment by micker** [comment]
sorry i update my post with screen

**Comment by creecros** [comment]
working for me now.

**Comment by micker** [comment]
yes thanks
