### ISSUE TITLE
Bug? Logging in, results in favicon

### ISSUE THREAD

**Issue by aljawaid** [creecros/Customizer#12]
Hello

When I login, it randomly takes me to display my `favicon` file only.  If I go back a page in my browser, Kanboard then (correctly) takes me to the dashboard.  The url when I have logged in, which displays only the favicon onscreen is: `https://domain.co.uk/kanboard/?controller=CustomizerFileController&action=image&plugin=customizer&file_id=1`

It happens randomly.  _Possibly_ at the start of each browser session.

**Comment by creecros** [comment]
it does it to me too. haven't figured out why, but for me, it seems when i restart my server while i was logged in. When I go to look into it, everything works fine....

**Comment by creecros** [comment]
actually, it does it when i clear cache, cookies and site data, then log back in.

**Comment by creecros** [comment]
Try now, make sure I'm not missing something before i close.

**Comment by aljawaid** [comment]
It seems to be fixed
