### ISSUE TITLE
header logo issue

### ISSUE THREAD

**Issue by jpdochy** [creecros/Customizer#122]
Hello,
clicking on KB leads to the dashboard, no prob.
After installation of Customizer, and uploading a new header logo, it appears where expected, but link does not work; it contains twice the link to the installation domain

Original KB header link : 
https://board.micylou.com/?controller=DashboardController&action=show

Link with header logo loaded by Customizer :
https://board.micylou.com/board.micylou.com/?controller=DashboardController&action=show

Installation info : 
Application version: 1.2.18
PHP version: 7.4.13
PHP SAPI: apache2handler
HTTP Client: cURL
OS version: Linux 5.4.0-58-generic
Database driver: mysql
Database version: 10.3.25-MariaDB-0ubuntu0.20.04.1

**Comment by creecros** [comment]
Unfortunately, I just tested with v1.2.18, and I did not have the same issue. 

Check your application settings URL just to make sure thats not where your issue lies: 
![image](https://user-images.githubusercontent.com/26339368/103948736-468a7780-5108-11eb-949f-190c613f615a.png)

**Comment by jpdochy** [comment]
Hello,

 

It looks just good ; if I remove the header logo, the letters KB are back, and the link works; I only have ths issue if I upload a new file (in this case the Micylou png image).

**Comment by creecros** [comment]
please list all your plugins in use. whatever your issue is, I dont believe its specific to customizer, as I just tested it, and there is no issue, so its clear to me, there is an unknown variable in play.

**Comment by jpdochy** [comment]
Here they are :

**Comment by creecros** [comment]
@jpdochy your list is empty, try logging into github to respond.

**Comment by jpdochy** [comment]
<img width="1355" alt="image" src="https://user-images.githubusercontent.com/42010946/103959731-c50b0780-5150-11eb-8952-256620c52e7e.png">

**Comment by creecros** [comment]
and just to confirm, Gantt is the last plugin on the list? I dont want to moss something. 


and did you see my previous reply?
Also, by defualt, it shouldnt be ?controller=DashboardController&action=show, should just be https://example.kanboard.com/dashboard, so....what's goin on there?

**Comment by jpdochy** [comment]
Update notifier is the last one, just under gantt, all others are on the screenshot.
And if I remove the header logo, uploaded with Customizer, it  works back all right... That's why I don't get it.
Application url : 
<img width="1336" alt="image" src="https://user-images.githubusercontent.com/42010946/103960475-81b19880-5152-11eb-8e17-bfae67648767.png">

**Comment by creecros** [comment]
ya, I dont either, ill do some tests, and see if I can find a conflict with all those plugins.

**Comment by creecros** [comment]
actually, I see your issue. its your application settings url. your missing the `https://`

**Comment by jpdochy** [comment]
Damn, that’s too stupid from me !

 

And therefore, I know where the double address comes from, it’s the htttp rewrite to https set up in Apache.

 

Thanks a lot for your support, it’s all solved now.

 

Cheers,

 

Jean-Paul

**Comment by creecros** [comment]
it was literally the first thing I told you to check 😜
