### ISSUE TITLE
Header logo 

### ISSUE THREAD

**Issue by jmd87fr** [creecros/Customizer#126]
Hi,
when I set a Header Logo and click I have an erreur message : Not Found  The requested URL was not found on this server.  
the url is : https://**my_site/kanban**/?controller=DashboardController&action=show
I need to change that because my kanboad is in https://**kanboard.my_site**.fr
I need your help :-)
Thank you

**Comment by creecros** [comment]
https://github.com/creecros/Customizer/issues/122

see this issue. it will solve ur problem

**Comment by jmd87fr** [comment]
Hi Creecros,
thank you 🥇 
I'm really sorry I didn't see that I had made a typing error in my url! [whip myself]

**Comment by creecros** [comment]
no worries
