### ISSUE TITLE
"login page note" not visible on login page 

### ISSUE THREAD

**Issue by tom5955** [creecros/Customizer#129]
configuration:
    Version: 1.2.20
    PHP Version: 7.3.33
    PHP SAPI: cgi-fcgi
    HTTP-Client: cURL
    OS Version: Linux localhost 3.10.0-1160.36.2.el7.x86_64 #1 SMP Linux localhost 3.10.0-1160.36.2.el7.x86_64 #1 SMP
    Datenbanktreiber: mysql
    Datenbank Version: 5.7.33-log
    Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:91.0) Gecko/20100101 Firefox/91.0

plugin version: 1.13.7

**Comment by creecros** [comment]
only in version 1.2.20? 
are you using any other plugins?

I dont see anything new in 1.2.20 that would cause it to break.

anymore info?

**Comment by tom5955** [comment]
we've installed these plugins in addtion to the "Customizer" 
1. Group_assign
2. Auto Subtask Creation
3. Greenwing

**Comment by tom5955** [comment]
we've installed 1.2.20 only

**Comment by creecros** [comment]
Greenwig. 99.99999% sure that's the reason.

**Comment by creecros** [comment]
I might as well explain.  Greenwig is a theme, and it overrides some of the same templates as Customizer, so, if you want the two plugins to work together, you would need to customize some code in the templates, depending on which override is being used.

**Comment by tom5955** [comment]
Thank's for your effort!

Best Regards
Tom
