### ISSUE TITLE
Avatar Icons: Deprecated: Required parameter $size

### ISSUE THREAD

**Issue by ArmReu** [creecros/Customizer#131]
Deprecated: Required parameter $size follows optional parameter $css in .../plugins/Customizer/Helper/DynamicAvatar.php on line 26

Deprecated: Required parameter $size follows optional parameter $css in .../plugins/Customizer/Helper/DynamicAvatar.php on line 47

No avatar image for header or board can be uploaded

![image](https://user-images.githubusercontent.com/22612373/151888673-4e65e807-d78a-44ba-98e7-c0defe0a6da3.png)

**Comment by creecros** [comment]
I'm not really maintaining this plug in anymore. sorry.

It sounds like your php version may be too new, try php 7.x

**Comment by wlangemeyer** [comment]
it's PHP 8 with the kanboard docker image v1.2.22 and I got the same issues/warnings

**Comment by wlangemeyer** [comment]
hi, I fixed it in this way and it's tested with php 7.4 and 8 and works for me.

# diff Customizer/Helper/DynamicAvatar.php Customizer/Helper/DynamicAvatar.php.fixed
26c26
<     public function dynamic($user_id, $username, $name, $email, $avatar_path, $css = '', $size)
---
>     public function dynamic($user_id, $username, $name, $email, $avatar_path, $css = 'avatar-left', $size = 48)
47c47
<     public function boardDynamic($user_id, $username, $name, $email, $avatar_path, $css = '', $size)
---
>     public function boardDynamic($user_id, $username, $name, $email, $avatar_path, $css = 'avatar-left', $size = 48)

sorry, I'm not familiar with git/github to commit/send you the file...

**Comment by creecros** [comment]
perfect execution. I'll merge your pull request when I get the chance.

**Comment by palcarazm** [comment]
Fixed by 908de2168d4caac47fb4448b46b6430c0c6851c0

**Comment by Jieiku** [comment]
Actually pretty sure this was already fixed here: https://github.com/creecros/Customizer/pull/132

**Comment by creecros** [comment]
im slacking, and haven't updated any releases in probably a year, so there are plenty of new merges that haven't actually been released.

**Comment by Jieiku** [comment]
oh ok, i can help with this. I will take a look at the repos soon, might have time tomorrow.

**Comment by Jieiku** [comment]
I drafted a new release: https://github.com/creecros/Customizer/releases/tag/1.13.8

and submited a pull request to update the plugin repo: https://github.com/kanboard/website/pull/310

**Comment by creecros** [comment]
you rock, thanks @Jieiku

**Comment by Jieiku** [comment]
no problem, happy to help.
