### ISSUE TITLE
Recreating folders outside root directory in cpanel

### ISSUE THREAD

**Issue by DickeyFuller** [creecros/Customizer#136]
In cpanel, with each cron run, this plugins recreates folders outside de root directory: plugins /  Customizer /  Assets / css / userthemes

**Comment by creecros** [comment]
indeed it does, should happen more than that.

**Comment by DickeyFuller** [comment]
Sorry for the bad explanation

The cron job recreates the folders with this path /home/user/plugins/Customizer/Assets/css/userthemes 
instead of /home/user/kanboard/plugins/Customizer/Assets/css/userthemes which is where the web site resides

**Comment by creecros** [comment]
I literally have no idea what you mean. please provide as much detail as you possibly can, i.e. what exactly are you doing, steps to recreate, etc...

**Comment by creecros** [comment]
https://github.com/creecros/Customizer/blob/8ff94950eda0ac22a2aece9590263da4949884bc/Plugin.php#L33-L43

this is where it happens, make sure you DATA_DIR is setup correctly in config. I still don't know what exactly what you are doing or how to achieve this result, but best I can offer.

**Comment by DickeyFuller** [comment]
I have a kanboard installation in a cpanel environment in /home/myuser/kanboard

With each cron job run, it creates this folder strcuture /home/myuser/plugins/Customizer/Assets/css/userthemes

I have solved in this way

`	// Themes
	if (!file_exists('/home/myser/kanboard/plugins/Customizer/Assets/css/userthemes')) { mkdir('/home/myuser/kanboard/plugins/Customizer/Assets/css/userthemes', 0755, true); }
	$customizer['themes'] = array(
		'Default' => '/home/myuser/kanboard/plugins/Customizer/Assets/css/theme.css'
		);`

**Comment by creecros** [comment]
good stuff. closing.
