### ISSUE TITLE
Tooltip "Dashboard" vanishes with new "Customized" Header Image

### ISSUE THREAD

**Issue by RainerBielefeld** [creecros/Customizer#139]
## STR
1. Install "Customizer"
2. ˋLaunch Customizer → function "Header Image" → Upload new Header Imageˊ
3. Go to Project /Pinboard View
4. Hover mouse pointer over new Header Image (which has replaced KANBOARD logo)
   » Expected: Tooltip "Dashboard"
     Actual: no Tooltip

  
## My Configuration
* KANBOARD Application version: 1.2.24 on all-inkl.com
* PHP version: 7.4.28
* PHP SAPI: fpm-fcgi
* HTTP Client: cURL
* OS version: Linux  5.4.0-131-generic
* Database driver: mysql
* Database version:  10.5.16-MariaDB-1:10.5.16+maria~focal-log
* Profile Language: German
* [Plugins](https://kanboard.org/plugins.html):
   * [AddMermaid](https://github.com/euneuber/AddMermaid) 0.1.0
   * [AgileIndicators](https://github.com/aljawaid/AgileIndicators) 1.0.0
   * [AutomaticActionUX](https://github.com/aljawaid/AutomaticActionUX) 1.6.0
   * [Broadcast](https://github.com/kanboard/plugin-broadcast) 1.0.1
   * [Chat](https://github.com/kanboard/plugin-chat) 1.0.3
   * [Customizer](https://github.com/creecros/Customizer)  1.14.0
   * [Group assignment for tasks](https://github.com/creecros/Group_assign) 1.7.12
   *  [KanboardSearch](https://github.com/ipunkt/KanboardSearch)      1.1.0
   * [KanboardEmailHistory](https://github.com/aljawaid/KanboardEmailHistory)  1.2.0
   * [KanboardSupport](https://github.com/aljawaid/KanboardSupport) 1.5.0
   * [MarkdownPlus](https://github.com/creecros/MarkdownPlus)  1.1.0
   *  [Paste image to markdown](https://github.com/Chaosmeister/PITM) 1.0.3
   * [Plugin Registration v1.0.8](https://github.com/kanboard/plugin-registration/)
   * [ProjectInvitation](https://github.com/ipunkt/KanboardProjectInvitation)   1.0.0
   * [Self-Registration](https://github.com/kanboard/plugin-registration)  1.0.8
   * <s>TaskProgressBar</s>
   * [SubtaskDescription](https://github.com/shaun-fong/Subtaskdescription) 1.1.1
   * [Task2Pdf](https://github.com/creecros/Task2pdf)  1.5.0
   * [Wiki](https://github.com/funktechno/kanboard-plugin-wiki)  0.3.0
* Browser: **SeaMonkey** 2.53.14 Beta pre, Build-Identifikator: 20220801210005  (Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:68.0) Gecko/20100101 Firefox/68.0)

**Comment by creecros** [comment]
I could argue that the tooltip "Appeared"  in a KB release within the past 4 years. Easy to add though.
