### ISSUE TITLE
Compatibility with PHP8.1

### ISSUE THREAD

**Issue by gituser317** [creecros/Customizer#140]
Updating Ubuntu to version 22.04. with PHP8.1 leads to error 500 when visiting Kanboard. In apache2 error log the following error is shown: 

PHP Fatal error:  Uncaught TypeError: array_diff(): Argument #1 ($array) must be of type array, bool given in /var/www/kanboard/plugins/Customizer/Plugin.php:27\nStack trace:\n#0 /var/www/kanboard/plugins/Customizer/Plugin.php(27): array_diff()\n#1 /var/www/kanboard/app/Core/Plugin/Loader.php(127): Kanboard\\Plugin\\Customizer\\Plugin->initialize()\n#2 /var/www/kanboard/app/Core/Plugin/Loader.php(67): Kanboard\\Core\\Plugin\\Loader->initializePlugin()\n#3 /var/www/kanboard/app/ServiceProvider/PluginProvider.php(27): Kanboard\\Core\\Plugin\\Loader->scan()\n#4 /var/www/kanboard/vendor/pimple/pimple/src/Pimple/Container.php(297): Kanboard\\ServiceProvider\\PluginProvider->register()\n#5 /var/www/kanboard/app/common.php(58): Pimple\\Container->register()\n#6 /var/www/kanboard/index.php(6): require('...')\n#7 {main}\n  thrown in /var/www/kanboard/plugins/Customizer/Plugin.php on line 27

**Comment by creecros** [comment]
what makes you suspect php 8.1?

what version of customizer and kanboard?

**Comment by creecros** [comment]
ya looking at this, seems to me you have something going on with a folder location. 

if I had to go oit on a limb, im guessing your upgrade changed some folder permissions.

**Comment by gituser317** [comment]
Appreciate your fast answer.
I suspect php8.1 because its a php fatal error and the php version has changed from 7.x due the update.
We use customizer 1.13.8 (already tried 1.14.0) and kanboard 1.2.24.


I rolled back the snapshot and checked folder permissions:

![Screenshot 2023-01-05 063558](https://user-images.githubusercontent.com/32760949/210713588-98a53991-cb0e-44ad-9704-2e0c9cc056fc.png)

After do-release-upgrade from 20.04. to 22.04. the folder permissions haven't changed:

![Screenshot 2023-01-05 070558](https://user-images.githubusercontent.com/32760949/210713604-8ded9c75-23c9-46c0-b0c0-7522d09f79db.png)

If a delete the Customizer folder in /var/www/kanboard/plugins kanboard starts normally. If i copy it back i am getting the error 500 in browser.

**Comment by creecros** [comment]
this has been thoroughly tested with php8.1, and you would only get php warnings, not fatal errors, if it was a php version issue.

your error is this:
`PHP Fatal error: Uncaught TypeError: array_diff(): Argument https://github.com/creecros/Customizer/pull/1 ($array) must be of type array, bool given in /var/www/kanboard/plugins/Customizer/Plugin.php:27\`

which points to line 27 of plugin.php:
https://github.com/creecros/Customizer/blob/b299fa4ec05cef7e8dfda70c76f95b80041e7d58/Plugin.php#L27

argument 1 of array_diff specifically points to:
`$plugin_folder.'/Customizer/Assets/css/userthemes`

so, that's your problem. period, end of story. either it doesn't exist, can't be found, or there is a permissions error on where it thinks it should exist. 

another thing to check is `PLUGIN_DIR` in your config.php, make sure it's defined correctly.

**Comment by gituser317** [comment]
Short answer: you are correct.

In fact the folder userthemes didn't exist and the web server had no permission to create it.
The command chown -R www-data:www-data /var/www/kanboard/plugins solved this issue.

Don't know why this leads to an error 500 only after the release upgrade and not before.

Thank you.

**Comment by creecros** [comment]
it's a crucial folder, customizer cant function without it. when you upgrade or install any customizer release, that folder will not exist, it has to create it. if it can't, for whatever reason, it's game over. the wiki for customizer is explicit with this. If I had motivation, I could put a bunch of stop measures in customizer and disable all theme functions when this folder can't be created, but then I'd have people not realizing why they can't use themes. but the bottom line is, folder permissions are imperative for customizer to function.

**Comment by creecros** [comment]
your apache logs also, might not be showing stderr logs, I don't see stderr in the messages, so a full view of stderr logs would show you everything going on, which would have showed us line 22 had an error, but that one would not stop the code and give you the 500. it's line 27 where the world breaks. but, having written the code, my first gut feeling of folder permissions, was the correct one, yes. without seeing line 22 error, though, it leaves a few other possibilities on the table.

**Comment by creecros** [comment]
oh and, you should be using latest version of customizer. v1.13.8 still has php 8.1 compatibility issues. specifically related to the dynamic avatar previews.
