### ISSUE TITLE
Custom header logo linking to default port 80 instead of actual instance port

### ISSUE THREAD

**Issue by huguesderiau** [creecros/Customizer#143]
If your Kanboard instance is accessible via different port number from the default 80, the header logo links to localhost/dashboard instead of localhost:[port_number]/dashboard.
See screenshots for my installation on port 8077 
![Screen-Shot-2023-02-25-at-10 36 06-AM](https://user-images.githubusercontent.com/72530102/221374334-72121638-2d68-4a11-8737-7d15308ba77f.gif)
![Screen-Shot-2023-02-25-at-10 39 10-AM](https://user-images.githubusercontent.com/72530102/221374335-3083f2c8-548f-4f87-9bb1-75f1be528a78.gif)

**Comment by creecros** [comment]
i dont know anything about how customizer would interact with "WeKanboard", so something to think about.

However, go to Apllication settings, and make sure you put in your Application URL with the Port.
![image](https://user-images.githubusercontent.com/26339368/221377871-feb09377-c85a-4f13-ab36-3a754f228646.png)

See if that fixes your issue.

**Comment by huguesderiau** [comment]
Hi Craig

Issue solved after setting my Application URL with the port number. the
value was previously blank.

Thank you for your quick answer!
