### ISSUE TITLE
Plugin version outdated

### ISSUE THREAD

**Issue by dxtr0dsgnz** [creecros/Customizer#144]
Hi,
minor issue: https://github.com/creecros/Customizer/releases/download/1.14.2/Customizer-1.14.2.zip identifies as 1.14.1.

`    public function getPluginVersion()
    {
        return '1.14.1';
    }
    `
Leads to constant notifications of plugin update notifier.

Best, Julian

**Comment by creecros** [comment]
Crap, did I forget to update the plugin.php

**Comment by creecros** [comment]
Ya apparently I did forget, I'll update the zip when I get a chance.

**Comment by RainerBielefeld** [comment]
fixed in code on github, but still unfixed in the zips

**Comment by creecros** [comment]
release zip is updated now

**Comment by RainerBielefeld** [comment]
Yes, now updates ends with new Version  1.14.2 in Plugins overview.
