### ISSUE TITLE
Customizer layout is messed up

### ISSUE THREAD

**Issue by bevstarr** [creecros/Customizer#148]
Hello good day

I have been using Customizer in my install for some time now.  After the initial setup and configuration years ago I haven't had a reason to come back to it until recently.  Over the past several years I have just updated the plugin and new versions were released and since everything worked I had zero reason to click on the plugin to make any changes to the site.  I've added plugins over that time and what needed to work as far as those plugins and the look and feel of the site continued to work. Recently I did an upgrade as I usually do with the intent of changing the look and field and try a more modern look.  That is when for the first time in a very long time I opened the plugin and it is not as it supposed to be.  I thought it would be a plugin conflict but I am not seeing anything to indicate as such.  I have attached a screenshot of how it looks for me.  Any ideas as to why or how this is the way it is and how do I go about fixing it would be appreciated.

![image](https://github.com/creecros/Customizer/assets/4682661/1cd03d25-8b53-4930-ad19-49ad0b645b94)

Thanks in advance 

Bevan

**Comment by bevstarr** [comment]
Nevermind. Found the offending plugin. Board Customizer

**Comment by KoljaL** [comment]
Is there a way to use them both?

**Comment by creecros** [comment]
I would report the issue to said offending plugin.
