### ISSUE TITLE
theme selector not displayed for users

### ISSUE THREAD

**Issue by gerald2545** [creecros/Customizer#149]
Hi,
thank you for your plugin. I installed it through kanboard 1.2.35 UI.
I can manage the Customizer settings....but as a user I found no way to select among the predefined themes coming with Customizer (I only have kanboard default theme selector) :   
![image](https://github.com/creecros/Customizer/assets/10177830/8fb2512b-eeb3-4b66-87ee-1b16c72bf7a2)

any idea?

Thank you for your help

Gérald

**Comment by creecros** [comment]
Did you enable user themes in the setting panel?

![image](https://github.com/creecros/Customizer/assets/26339368/8750836e-3739-4c0e-9ec8-9fb9f6bbc6a7)

**Comment by gerald2545** [comment]
OMG!! sorry, I just not scrolled enough...it's OK now!!!

sorry again!!
