### ISSUE TITLE
Earlier Kanboard Compatibility

### ISSUE THREAD

**Issue by creecros** [creecros/Customizer#16]
```*47 FastCGI sent in stderr: "PHP message: PHP Warning:  filemtime(): stat failed for assets/css/print.min.css in /var/www/app/app/Helper/AssetHelper.php on line 37```

@aljawaid @kenlog  any idea? I'm clueless what this is about. 

not getting it in 1.2.5 or 1.2.6, but 1.0.45 is ringing it

**Comment by creecros** [comment]
has to do with the .css being loaded
```    public function css($filename, $is_file = true, $media = 'screen')
    {
        return '<link rel="stylesheet" href="'.$this->helper->url->dir().$filename.($is_file ? '?'.filemtime($filename) : '').'" media="'.$media.'">';
    }
```

**Comment by creecros** [comment]
also getting PHP Notice:  A non well formed numeric value encountered in /var/www/app/app/Helper/TextHelper.php

**Comment by aljawaid** [comment]
@creecros sorry I don't have a clue either.  I don't think it's the css as much as the way Kanboard is finding it.

**Comment by creecros** [comment]
yeah that worked for that one:
b74676a9149757737d37dd8c9081c0daf83e67a2

**Comment by creecros** [comment]
solved both.
