### ISSUE TITLE
Placeholder

### ISSUE THREAD

**Issue by aljawaid** [creecros/Customizer#17]
I'm trying to add a placeholder but I keep getting:
`Content Security Policy: The page's settings blocked the loading of a resource at inline ("default-src").`

I've tried:
```
<script>$('#form-username').attr('placeholder', 'Search for Stuff');</script>
```
and
```
<script async type="text/javascript">document.getElementById("form-username").setAttribute("placeholder", "Enter your username");</script>
```
in `/logintop.php`.  Any suggestions?  You can't add a placeholder using pure css, must be javascript or jquery.

**Comment by creecros** [comment]
show me exactly what you are doing. you can only pass global variables into logintop.php, since no one is logged in, there are no permissions established.

**Comment by aljawaid** [comment]
On the login page:
`<input type="text" name="username" id="form-username" class="required" autofocus>
and 
`<input type="password" name="password" id="form-password" class="required">` must be `<input type="password" name="password" id="form-password" placeholder="Enter your password" class="required">`

So basically both input fields need the attribute `placeholder="some text"` added to them.

**Comment by creecros** [comment]
I'll take a look tonight
