### ISSUE TITLE
session_exists() in Ealerier Version Kanboards

### ISSUE THREAD

**Issue by creecros** [creecros/Customizer#21]
On version 1.0.45
PHP message: PHP Fatal error:  Uncaught Error: Call to undefined function session_exists() in /var/www/app/plugins/Customizer/Template/layout/logintop.php

I need to look into this.

**Comment by creecros** [comment]
people don't like upgrading? plus it poses a challenge!

**Comment by kenlog** [comment]
I like your tenacity! Here is another plugin definitely to do, make the automatic update of Kanboard "with a click" :zap:

**Comment by creecros** [comment]
That'd be nice, but I'm a docker user, it already is a click ;p

**Comment by kenlog** [comment]
Docker i find it a real convenience but above all what you need when you need it, without wasting system resources.

**Comment by kenlog** [comment]
I see you've done it. That's okay

**Comment by creecros** [comment]
Yeah, looks like session_exists() didn't actually exist in v1.1.1 and below, was introduced in v1.2.0

**Comment by creecros** [comment]
of course, now i notice the favicon doesn't work until your logged in in v1.0.45...

**Comment by creecros** [comment]
crap, now it's all versions....

**Comment by creecros** [comment]
what did we change?

**Comment by kenlog** [comment]
I thought to avoid this problem, we could use a "static" storage by saving the files in a folder of the plugin. What do you say?

**Comment by creecros** [comment]
if you can figure it out, I tried this early on and could figure it out

**Comment by creecros** [comment]
ok, so, it does work....after i reuploaded a favicon....i'm wondering how it lost it though. maybe my switch to 1.0.45, or is it a cache thing and it isn't really working.....and I just think it works.

**Comment by creecros** [comment]
> I like your tenacity! Here is another plugin definitely to do, make the automatic update of Kanboard "with a click" ⚡️

and if you figure this out, figure out how to restart the kanboard, because i hate having to restart the server even after a plugin update

**Comment by kenlog** [comment]
Sometimes the cache makes bad jokes even to me.

**Comment by creecros** [comment]
well, i know i'm not using the cache for any of these images, intentionally didn't use it because it would take 5 * 86400 seconds to actually see your new logo....but maybe the favicon doesn't care about that...and caches it anyway.

**Comment by creecros** [comment]
and now that i think about, i should put a limit on the `size` feature....what if someone puts 200000 in there...

**Comment by kenlog** [comment]
Why do you also restart a plugin update? It should not be necessary

**Comment by creecros** [comment]
it is for me....maybe it's a docker thing?

**Comment by kenlog** [comment]
> > I like your tenacity! Here is another plugin definitely to do, make the automatic update of Kanboard "with a click" zap
> 
> and if you figure this out, figure out how to restart the kanboard, because i hate having to restart the server even after a plugin update

Why do you also restart a plugin update? It should not be necessary

**Comment by creecros** [comment]
here https://projects.creecros.ml/ admin,admin

update the customizer plugin, watch what happens

**Comment by creecros** [comment]
then restart it:
https://dock.myplacenow.ml

kenlog
kenlog123

**Comment by kenlog** [comment]
You do not update, do this test change php version

**Comment by creecros** [comment]
who what?

**Comment by creecros** [comment]
Configuration
Application version: 1.2.6
PHP version: 7.2.10
PHP SAPI: fpm-fcgi
OS version: Linux 4.9.45-rancher
Database driver: sqlite
Database version: 3.24.0
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36

**Comment by kenlog** [comment]
Very strange I do not know what can depend in particular.

**Comment by kenlog** [comment]
for sure there is something that does not update in real time

**Comment by kenlog** [comment]
> lol 'who what?' is an expression...like 'say what?' or 'i didn't understand what you were asking me to do?' sorry, forget that your not a silly american like me

I was asking you to try changing the PHP version

**Comment by kenlog** [comment]
Forgive me my english is not the best :grimacing:

**Comment by creecros** [comment]
no worries. thinks it's pretty good.

the 1.0.45 container is using php 7.1.5, it still does it. I can try and finder and older docker image with php 5.6. not sure i feel like making my own container.

**Comment by creecros** [comment]
1.0.30 - Customizer plugin doesn't work, im not going to bother trying 

Configuration
Application version: master.a1e2b0f1b88ed445a9dd960d9431fdbcf983fb33
PHP version: 5.6.21
PHP SAPI: fpm-fcgi
OS version: Linux 4.9.45-rancher
Database driver: sqlite
Database version: 3.13.0
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36

**Comment by kenlog** [comment]
I can guarantee you that the following PHP versions 7.0.31 and 7.1.23, I do not find any problem

**Comment by kenlog** [comment]
It could be something else to cause this anomaly

**Comment by creecros** [comment]
well, good news, update notifier actually somewhat works, but no affect to plugin updates needing restart

![image](https://user-images.githubusercontent.com/26339368/47581771-6f0b6a00-d920-11e8-99c7-14f94ce3a7a0.png)

**Comment by creecros** [comment]
must be something else

**Comment by kenlog** [comment]
in reality the notifier should not influence the plugin update. This is because the update is managed by Kanboard

**Comment by creecros** [comment]
i meant, good news, that your plugin somewhat works in Kanboard v1.0.30

**Comment by kenlog** [comment]
Excellent news! [So we can change compatibility](https://github.com/kenlog/UpdateNotifier/blob/master/Plugin.php#L40)

**Comment by creecros** [comment]
no, it functions, but there are layout issues you'd have to account for, the biggest one being:
https://github.com/kenlog/UpdateNotifier/blob/master/Template/plugin/directory.php

**Comment by kenlog** [comment]
Before `$this->url->link` now `$this->url->icon`

**Comment by creecros** [comment]
you could do >=1.0.42, tsted in 1.0.45, works fine, nothing really changed down to 1.0.42

**Comment by creecros** [comment]
your welcome to spin up images on that test server, FYI, if you need to.

**Comment by kenlog** [comment]
I thank you, now I'm going out to dinner. See you soon
