### ISSUE TITLE
Rename "Use Custom Colors" and use checkbox to switch between "Basic" and "Advanced settings"

### ISSUE THREAD

**Issue by vistree** [creecros/Customizer#24]
This is a feedback to the [creecros-test-1 branch](https://github.com/creecros/Customizer/tree/creecros-test-1)!
basic: settings from current master-branch (image-settings + URL settings + ...)
advanced: color settings + font-settings
If we go with the current dropdown, make sure "NO" is the default value

**Comment by creecros** [comment]
Using a checkbox should be no problem, i threw the dropdown in just as a quick testing mechanism. Pretty sure it defaults to 'NO' though.

**Comment by vistree** [comment]
Retested creecros-test-1 branch on fresh install - and "Use Custom Colors" default is YES

**Comment by vistree** [comment]
Same for Theme-Presets branch

**Comment by creecros** [comment]
> Same for Theme-Presets branch

"Use Custom Colors" doesn't exist in Theme-Presets branch?

**Comment by creecros** [comment]
For the Test branch, changing:
https://github.com/creecros/Customizer/blob/725609223913d7563183950173875cc5e2d1f0e4/Plugin.php#L25

to 

` if ($this->configModel->get('useCustomColors', '1') == '0') {`

should correct that. `1` is NO and `0` is 'YES'

**Comment by creecros** [comment]
actually no, I'll have to store a value before it tries to read it the first time, all of which is meaningless if we are changing it to a check box.

**Comment by vistree** [comment]
I still would think about this! Maybe users want to set only images?!

**Comment by creecros** [comment]
agree, currently, they can opt out of using a theme by choosing the "Default" theme, but an option to not affect the login panel/page could easily be implemented as well. I will look at that some more.

**Comment by creecros** [comment]
#56 and #57 

Customizer can now be used for settings images with other features all turned off completely.
