### ISSUE TITLE
Store settings in file-system

### ISSUE THREAD

**Issue by vistree** [creecros/Customizer#25]
This is a feedback to the [creecros-test-1 branch](https://github.com/creecros/Customizer/tree/creecros-test-1)!
create a css-file on storage instead of storing the settings in the database.
I think, file system is faster and if somewhen theme cacheing is enabled this will not work with database settings.
When visiting the customizer settings page, current settings have to be parsed from the current CSS (custom css created by previous customizer savings) or from current active theme (nebula, standard theme, moon, ...)
Using file system would it easier to allow other plugins to provide additional presets

**Comment by creecros** [comment]
I can try to do this. With the image files, i had originally started this way, but ran into file permission problems, but I think it should be fine if the files remain in the plugin directory.

**Comment by vistree** [comment]
I think we can close this issue as it is part of the general discussion already
