### ISSUE TITLE
Color groups

### ISSUE THREAD

**Issue by vistree** [creecros/Customizer#27]
This is a feedback to the [creecros-test-1 branch](https://github.com/creecros/Customizer/tree/creecros-test-1)!
Maybe we can define color groups by looking at existing theme-plugins to see where the same color is used in different theme regions.
This would reduce the number of color switchers which is currently to high (from my point of view)

**Comment by creecros** [comment]
Not perfect, and needs work, but it is a start
https://github.com/creecros/Customizer/releases/tag/1.8.0
