### ISSUE TITLE
Additional settings

### ISSUE THREAD

**Issue by vistree** [creecros/Customizer#28]
This is a feedback to the [creecros-test-1 branch](https://github.com/creecros/Customizer/tree/creecros-test-1)!
maybe we can create groups for different regions of the theme. E.g. header settings
here we can offer "font-family, font-size, color, logo, site name, site-name color, site-name font-family, site-name font-size, link color, link color hover, ...)

**Comment by creecros** [comment]
https://github.com/creecros/Customizer/releases/tag/1.8.0
