### ISSUE TITLE
Stay on Customizer settings page after saving settings

### ISSUE THREAD

**Issue by vistree** [creecros/Customizer#29]
This is a feedback to the [creecros-test-1 branch](https://github.com/creecros/Customizer/tree/creecros-test-1)!
If you want to make advanced adjustments, the user would open an additional browser tab to display the current changes. So it would be better if after saving the settings we could stay on the Customizer Settings page instead of forwarding them /?controller=DashboardController&action=show&user_id=1

**Comment by creecros** [comment]
I believe I already did this, but the test branch is behind, just need to merge master into test branch.

**Comment by creecros** [comment]
Actually, it should already be doing this, is it not?

**Comment by vistree** [comment]
Since we seem to have several different plugin behaviors, I will test again with a fresh installation.

**Comment by creecros** [comment]
Making a new branch for Theme Presets. Think we should work that out first, and then come back to "Custom Color Pickers", I'll leave the current [creecros-test-1](https://github.com/creecros/Customizer/tree/creecros-test-1) branch for reference until then.

**Comment by vistree** [comment]
Retested with new Theme-Presets branch - same problem After clicking "save" I am redirected to http://www.kanboard.local/settings/customizer
Navigating to the Customizer settings page shows 
http://www.kanboard.local/?controller=CustomizerFileController&action=show&plugin=Customizer instead

**Comment by creecros** [comment]
that's correct, it's a defined route
https://github.com/creecros/Customizer/blob/9bf0380fb619f1b22664beeb391f51b9eede7ede/Plugin.php#L59

**Comment by creecros** [comment]
![](https://github.com/creecros/empty/blob/master/redirect.gif?raw=true)

**Comment by vistree** [comment]
That's wired - application URL is set!! But just recognised, that I can't checkout the Theme-Presets branch. Therefor I changed code in creecros-test-1
Can you have a look for my changes and if they work for you?

**Comment by vistree** [comment]
OK, committed to Theme-Presets branch - can you have a look?

**Comment by creecros** [comment]
Yeah, it works.

**Comment by creecros** [comment]
Let me spin up a fresh server, just incase, double test.

**Comment by creecros** [comment]
probably not, I tried to do it without adding that controller, only added it so I could redirect. copied from kanboard configcontroller.

**Comment by creecros** [comment]
doesn't look relevant, go ahead and remove.

**Comment by vistree** [comment]
Done in Theme-Presets branch ;-)

**Comment by creecros** [comment]
Will merge once we get the Theme presets finalized. Can close this for now. Let me know what you think about the Theme function.

**Comment by vistree** [comment]
What do you mean with Theme function? The css-load on plugin initialisaiton?

**Comment by creecros** [comment]
Referring to the entire theme selection functionality in that branch.
