### ISSUE TITLE
No CSS file?

### ISSUE THREAD

**Issue by aljawaid** [creecros/Customizer#3]
Is there no way to customise the css of the plugin?

For the KanboardCSS theme plugin, this works:
```
.logo > a > img {vertical-align:middle;} /* This aligns the logo certically to the text */
.form-login > a > img {display: block;margin: auto;} /* This makes the logo centralised */
```

**Comment by creecros** [comment]
your the CSS expert ;p

**Comment by creecros** [comment]
can this be centered better in relation to the login panel?

![image](https://user-images.githubusercontent.com/26339368/47262921-f3925e80-d4c2-11e8-8915-d3596bf25b0d.png)

it bothers me being off center, i think i prefer left align. maybe I can add a choice.

**Comment by aljawaid** [comment]
I will check it out :)

**Comment by aljawaid** [comment]
@creecros It is actually not off centre, The input fields are making it look like that.  The bright blue box should make it clearer to identify.

![image](https://user-images.githubusercontent.com/10233708/47265810-5caabe00-d525-11e8-88a5-599f1164096d.png)

The padding and alignment is pretty out of place which looks fine on a white screen but not when adding logos or backgrounds.

With the unsplash setting it looks worse as the login text fields are not easily readable.

I will start working on it tonight if you don't beat me to it :)

**Comment by aljawaid** [comment]
@creecros Please check below, if you're happy with it, I will push it to the repo...

### **Without unsplash:**
![2018-10-21 22_35_35-window](https://user-images.githubusercontent.com/10233708/47272865-6400b480-d583-11e8-8969-f8e828c04027.png)

### **With unsplash:**
![2018-10-21 22_46_28-window](https://user-images.githubusercontent.com/10233708/47272871-7a0e7500-d583-11e8-8113-df2fde5a7342.png)

I left the login form on a white background in case users had logos without clear backgrounds.  Let me know what you think.

**Comment by creecros** [comment]
I like this a lot! But I'm thinking it should be an option that can be set to turn on. Thoughts?

**Comment by aljawaid** [comment]
Sorry I missed the notifications on this when Github was down, didn't realise you already asked for the changes.... they are done now, ready to be pushed

**Comment by creecros** [comment]
No worries
