### ISSUE TITLE
APP_VERSION is master

### ISSUE THREAD

**Issue by yvalentin** [creecros/Customizer#30]
An error happen if the APP_VERSION is equal to master.

So, i have this follwong error with this plugin.
Internal Error: Identifier "sessionStorage" is not defined.

https://github.com/creecros/Customizer/blob/3af19ee9c7d0b41f7867ae9a24bcfd2e59f39c61/Template/layout/logintop.php#L81

Could you fix this ?

**Comment by creecros** [comment]
I anticipated this, I'll have to think of a different way to determine the app version for installs that use "Master".

**Comment by creecros** [comment]
I think I got it:
`if (function_exists('session_exists')) {`
instead

**Comment by yvalentin** [comment]
I'm on 1.2.6.

Yes, I think just check if function exist can be a good way...

**Comment by creecros** [comment]
You can install manually or wait for the update to merge, let me know if you have any other issues.
