### ISSUE TITLE
[REQ]: Style the Login button

### ISSUE THREAD

**Issue by pixi** [creecros/Customizer#39]
The little blue "**SIGN IN**" doesn't really fit to a color scheme (if it's not blue itself). So, being able to style the button, colorwise, and maybe make it stretching the same width as the fields above would give the whole a much better first experience!

**Comment by creecros** [comment]
@vistree @kenlog @aljawaid 

I guess the question is: 

should the login button be separated from the buttons overall? Currently in dev, is the ability to customize theme presets, which would affect buttons in general.

**Comment by creecros** [comment]
So many options now...!

![image](https://user-images.githubusercontent.com/26339368/48282686-59ba3380-e428-11e8-933f-6542142a7e7b.png)

**Comment by creecros** [comment]
> you could add a class to the button and associate the customization with that class.

added class: `login-btn`

**Comment by kenlog** [comment]
Hi @creecros I have a correction to send, which corrects the position of the access button when the "Remember Me" field is in the false condition.

**Comment by creecros** [comment]
@kenlog just push it, i'll update release before it gets merged

**Comment by kenlog** [comment]
@creecros okay, I wanted your blessing :wink:

**Comment by creecros** [comment]
you earned my blessing when i gave you collaborator, so i trust you 😛

**Comment by creecros** [comment]
might as well make those radius corners the same while your at it, if you don't mind

**Comment by kenlog** [comment]
thank you so much! :+1:

**Comment by creecros** [comment]
i got the radius. updating release.

**Comment by kenlog** [comment]
The border radius inside `.form-login` already present in the previous version https://github.com/creecros/Customizer/blob/7f8c7d8db9a03c76a42828dfbcf781422cad7015/Template/layout/logintop.php#L18. I was trying to figure out where it was missing. The next I will try to be more reactive, promised! :innocent:

**Comment by creecros** [comment]
No worries! I had a minute before a meeting, and beat you to it.

@pixi thanks for the email, we're glad you find this plugin useful!

![image](https://user-images.githubusercontent.com/26339368/48288689-fab1ea00-e43a-11e8-9223-8596257f757a.png)

**Comment by kenlog** [comment]
@creecros arranged with the commit 4a4d3c3aacf0392338013da4d0563138645b7fa2
