### ISSUE TITLE
Support

### ISSUE THREAD

**Issue by kenlog** [creecros/Customizer#4]
Hi creecros, congratulations for the very useful plugin! I am writing to inform you that I have supported Customizer in the following themes [Moon](https://github.com/kenlog/Moon), [Nebula](https://github.com/kenlog/Nebula) ;-)

**Comment by kenlog** [comment]
I'm glad you like Nebula! If you want to contribute to the theme feel free to do it :wink:

**Comment by creecros** [comment]
this '.' is how much i know about css and js, but it looks like bak2top inspired you at least 😄

**Comment by kenlog** [comment]
Yes, it's true! :+1:

**Comment by creecros** [comment]
Moon Issue:

* Header seems wrong to me
![image](https://user-images.githubusercontent.com/26339368/47263175-55a29200-d4ca-11e8-94e3-a05b13349061.png)

* Seems wrong on Nebula to, hard to tell, i could be wrong
![image](https://user-images.githubusercontent.com/26339368/47263226-1c1e5680-d4cb-11e8-8c51-6245884f0b92.png)

**Comment by kenlog** [comment]
Hello creecros, in moon you can change the color of the title. [Look here](https://github.com/kenlog/Moon/blob/1ca83474c73a00d14ce684d5cac7e173957e626b/config.php#L14)
Instead nebula from the screen seems good to me

**Comment by creecros** [comment]
Never even noticed that

**Comment by kenlog** [comment]
I took a look and forgot to declare the [variable](https://github.com/kenlog/Moon/blob/616566e48ccd8755512d7ff0b95126f95d32d1ab/Template/layout/header/customizerTitle.php#L1) that assigns the color code. Many thanks @creecros ! :1st_place_medal:
