### ISSUE TITLE
Semantic versioning specification 

### ISSUE THREAD

**Issue by kenlog** [creecros/Customizer#42]
Hi @creecros the version it should probably already be 1.0.0 following the directions [Semantic Versioning](https://semver.org/#spec-item-2) I prefer this kind of approach :one:.:two:.:zero: . Is clear does not want to be a reminder to use the "Semantic Versioning" I would just like to deepen this topic with you, thank you. :innocent:

**Comment by creecros** [comment]
I'm thinking that, on the next version, go to 1.0.0 and then follow semantic from there. Or should we go back and calculate where it should actually be?

**Comment by creecros** [comment]
let me know thoughts, before i make new release file.

Options:
1. next release v1.0.0
2. next release is a minor, to v1.8.0

**Comment by kenlog** [comment]
Hi @creecros using the semantic version specification we are at v1.6.0

**Comment by creecros** [comment]
roger, next release will be 1.7.0
