### ISSUE TITLE
Suggestion messages

### ISSUE THREAD

**Issue by kenlog** [creecros/Customizer#49]
Hi @creecros in my opinion here you wanted to intend recommended width?
https://github.com/creecros/Customizer/blob/70769898276a1a9f94e032610edae58476b67bcb/Template/file/upload_logo.php#L4

**Comment by creecros** [comment]
correct, useless now that height is an option. there are no validation rules though to what you can upload, so the statement helps i guess.

**Comment by creecros** [comment]
Oh, now I understand, yes that should recommend 100px in width. but, can proabably just be removed. the only important part is file types, which should be obvious.

**Comment by creecros** [comment]
commit 35f967e197a741172b2c1f17a14632c83ac5e589
