### ISSUE TITLE
Login logo

### ISSUE THREAD

**Issue by kenlog** [creecros/Customizer#6]
Hello creecros, I noticed a small problem using a white logo on the login page, instead a white logo in the theme that has the dark header is fine, instead for the login page the logo on a white background is not displayed. My proposal is to add a dedicated logo upload for the login page. What do you say could solve?

**Comment by creecros** [comment]
Yeah, I could separate and use a dedicated slot for login logo.

**Comment by creecros** [comment]
Also, screenshot what the issue is

**Comment by kenlog** [comment]
Yes dedicated slot for the access logo is perfect! :+1: 
![login](https://user-images.githubusercontent.com/11728231/47258836-8f12d780-d4a1-11e8-875b-1e7d7286a150.jpg)
![header](https://user-images.githubusercontent.com/11728231/47258837-91753180-d4a1-11e8-83e1-1f0d46cd84bb.jpg)
