### ISSUE TITLE
Custom Themes are lost while upgrading

### ISSUE THREAD

**Issue by vincowl** [creecros/Customizer#67]
While upgrading plugin, own custom themes are erased. Would it be possible to avoid this and keep them declared in Customizer ?

**Comment by creecros** [comment]
Yes, it’s already been addressed in the css-generator branch, just hasn’t merged, as there are many new features that are currently in development. I’ll see about a patch until then.

**Comment by creecros** [comment]
https://github.com/creecros/Customizer/releases/tag/1.8.0
