### ISSUE TITLE
Upgrade troubles

### ISSUE THREAD

**Issue by vincowl** [creecros/Customizer#68]
While upgrading Customizer with the Kanboard Plugin Manager, it is still displayed as an old version in the "Installed Plugins" page while files have been properly installed and new version is running. This causes the UpdateNotifier plugin to display an erroneous "new upgrade available" message. Don't know if it's related to Customizer plugin or to internal Kanboard plugin management

**Comment by creecros** [comment]
Hmmm. I will investigate.

**Comment by vincowl** [comment]
Please have a look at the same [issue](https://github.com/kanboard/kanboard/issues/4084) I raised on kanboard's github. Seems that the problem relates with Plugin Manager since installation's status is badly displayed and that it concerns various plugins. No common denominator found yet.

**Comment by creecros** [comment]
![image](https://user-images.githubusercontent.com/26339368/49226380-5de8c980-f3b4-11e8-82fc-bfbffd5891e7.png)

I'm not getting the issue. 

Are you using Docker, per chance?

**Comment by vincowl** [comment]
Yes Docker version 18.06.1-ce, using docker-compose 1.21.0

**Comment by creecros** [comment]
Restart the container after you install the update, it should then show, "up to date"

**Comment by vincowl** [comment]
I just tried to remove the docker container and recreate it since plugins are persisted in mapped volumes. Indeed, the problem seems to be solved, at least with Customizer. Other plugins are still wrongly marked as not installed... Strange....
So : this issue can be closed since the problem is not linked to this plugin. Thanks !!
