### ISSUE TITLE
problem after plugin installation

### ISSUE THREAD

**Issue by kakitogit** [creecros/Customizer#70]
Hi, i have a problem after installing the Customizer plugin, i tried several times and everytime i install it the board page for all the projects appears blank (only the logo is showed) in the apache error log appears:

[Wed Dec 12 10:33:12.701216 2018] [:error] [pid 15582] [client 192.168.1.1:51477] PHP Warning:  Invalid argument supplied for foreach() in /var/www/html/board/plugins/Customizer/Plugin.php on line 30
[Wed Dec 12 10:33:12.793733 2018] [:error] [pid 15582] [client 192.168.1.1:51477] PHP Fatal error:  Call to undefined method Kanboard\\Helper\\AppHelper::tooltipHTML() in /var/www/html/board/plugins/Customizer/Template/header/title.php on line 23
[Wed Dec 12 10:33:12.935979 2018] [:error] [pid 13991] [client 192.168.1.1:51481] PHP Notice:  Undefined variable: scanned_user_themes in /var/www/html/board/plugins/Customizer/Plugin.php on line 30

what could i do?

Thanks.
Carlos.

**Comment by creecros** [comment]
@kakitogit 
Can you give me details about your install.

What version kanboard are you using, what other plug-ins do you have installed, etc?

**Comment by creecros** [comment]
Also, customizer v1.8.1 should take care of the notice and warmings, it's that fatal error that's killing it, not sure what that's about at first glance, definitely need your install details to troubleshoot that one.

**Comment by kakitogit** [comment]
those are my already installed plugins:
Bak2topbotm
Calendar
CommentTooltip
Creecros_Filter_Pack
Group_assign
Metadata
Milestone
Task2pdf
Wiki
Budget
CommentOnly
Coverimage
Gantt
KanboardCSS
MetaMagik
Subtaskdate
TaskIntervalButton

and the Kanboard version is: 
Application version: 1.2.2
PHP version: 5.6.37-0+deb8u1
PHP SAPI: apache2handler
OS version: Linux 4.9.35-v7+
Database driver: mysql
Database version: 5.5.60-0+deb8u1
Browser: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.110 Safari/537.36

Thanks a lot.

**Comment by creecros** [comment]
Perfect, give me a bit of time to figure it out. Stay tuned.

**Comment by creecros** [comment]
It's the kanboard version, I'll have a solve by end of day and update a new release.

Also, just a side note, no need for Metadata Manager and MetaMagik, MetaMagik includes all thee functionality of Metadata Manager.

**Comment by kakitogit** [comment]
ok, perfect!
so i will wait for your update and i will delete the Metadata Manager plugin, thnks for the hint

**Comment by kakitogit** [comment]
thanks a lot, i will test it and will let you know.

Thanks
