### ISSUE TITLE
Invalid argument supplied for foreach

### ISSUE THREAD

**Issue by loveprograming** [creecros/Customizer#72]
When installed customizer as a plugin for the first time, I got this warning: “Invald argument supplied for foreach() in Customizer/Plugin.php on line 30”.
I think this is caused by the condition check on line 23. Since I don't have files under “DATA_DIR/file/customizer/themes”, $scanned_user_themes has never been assigned which makes it invalid.
Moving the foreach block on line 30 into the condition check block on line 23 should remove this warning.
Please confirm this. Thanks.

**Comment by creecros** [comment]
I think I'm just going to create that folder if it doesn't exist, thanks for pointing that out. I'll update next chance I get.

For now, if you just make that folder, the warning will go away.

**Comment by creecros** [comment]
All set, moved into into the condition and makes the folder if it doesn't exist.
https://github.com/creecros/Customizer/releases/tag/1.8.3
