### ISSUE TITLE
Themes for individual users

### ISSUE THREAD

**Issue by alkgreer** [creecros/Customizer#81]
When i make changes to the theme all users get the theme changes. Is there a way for individual users to pick their own themes?

**Comment by creecros** [comment]
Customizer is global. 

It would require extensive development to incorporate themes as a user setting.

**Comment by creecros** [comment]
I always hit the wrong button...

**Comment by creecros** [comment]
I can envision how that would work, though....yikes....i'll look at that next time I'm bored.

**Comment by creecros** [comment]
@alkgreer @kenlog @vistree @aljawaid 

k, made this work.

Branch: https://github.com/creecros/Customizer/tree/user-theme

Working instance: https://projects.nachostudio.ml

user: admin pw: admin
user: test pw: test123

I placed the user theme selection on `My Profile>Edit Profile` found at the bottom of the page.
![image](https://user-images.githubusercontent.com/26339368/56628172-ca3fc000-6616-11e9-9a36-8444a0561a4f.png)

The previous Theme Selection in the Settings>Customizer page, is now the Default for all users who have not selected a theme.

I tested on two machines with two consecutive users running different instances and it had no issues, but would be cool if someone else could test, make sure I didn't miss anything.

let me know what you guys think, i might play with it a little bit more to make it a bit more pretty...I didn't like having 2 save buttons on that page, but, it was easier to just run through a controller i already had in Customizer as opposed to overriding the UserModificationController.

**Comment by creecros** [comment]
also, just noticed a behavior i'll need to change. selecting "default" on the user level will select the theme from Customizer Settings, and not the Kanboard "Default". it does this because 

https://github.com/creecros/Customizer/blob/0105cc22119c0262911ed83095eedf4370fcdcc1/Plugin.php#L39-L43

i was rewriting theme.css and hooking to the css asset in kanboard, but i don't need to do that. Next time i get bored, i'll switch that behavior.

**Comment by creecros** [comment]
- changed behavior, so default is now selectable by a user
- removed 2nd save button
- dropdown now auto submits onchange of theme
- moved theme feildset to top
![image](https://user-images.githubusercontent.com/26339368/56673281-f5152d00-6685-11e9-8e10-c1122dfa3a8f.png)

**Comment by creecros** [comment]
## To-Do
- [ ] Add an upload custom theme on manage themes accordion
  - I don't think it is out of the scope of what the plugin already does, and only admins can access this feature anyway.
- [ ] Add a reset all user themes button for admin
- [ ] Add toggle, to allow/disallow user theme selection

**Comment by creecros** [comment]
All set. 

Since I'm talking to myself, I'll just merge.

If any of you guys see an issue...let me know.
