### ISSUE TITLE
Issue with Preformatted Code

### ISSUE THREAD

**Issue by orware** [creecros/Customizer#82]
I don't know if you've noticed this on your end or not, but after starting to use Customizer a few weeks back I've noticed that it does something a little odd with the code formatting.

For the first line it'll indent it with an extra space:
![image](https://user-images.githubusercontent.com/931650/56437547-c4538300-6294-11e9-81e0-dfb18ad188c2.png)

I was going to try and fix it on my own, but at the moment cannot tell how it's even adding in that extra space, since in the HTML output it doesn't have any spaces being accidentally introduced:
```
<pre><code>slmgr.vbs -ipk XXXXX-XXXXX-XXXXX-XXXXX-XXXXX
slmgr.vbs -ato</code></pre>
```

Actually on an additional look into things as I'm writing this, I just figured out what's causing the issue...it appears to be the padding defined in the customizer.css file:

```
code {
	margin: 0;
	padding: 2px 0.4em;
	background-color: rgba(27, 31, 35, 0.32);
	border-radius: 3px;
	color: #fff;
	font-family: Tahoma;
	font-size: 95%!important;
	letter-spacing: 1px;
} /* This styles the url link examples */
```

When I remove the padding definition it goes back to normal:

![image](https://user-images.githubusercontent.com/931650/56437827-b81bf580-6295-11e9-905e-57b9d57de389.png)

**Comment by creecros** [comment]
You want to take care of it and make a PR, or you want me to do it?

**Comment by orware** [comment]
Put together a quick PR for you.

**Comment by creecros** [comment]
Good stuff, appreciate the contribution. I'll merge next chance I get
