### ISSUE TITLE
JavaScript Console Errors on Non-Customizer Pages Throughout Kanboard

### ISSUE THREAD

**Issue by orware** [creecros/Customizer#83]
This issue appears to occur since the customizer.js file gets loaded throughout the site when you're using Customizer and should show up in the Chrome DevTools Console:
![image](https://user-images.githubusercontent.com/931650/56438066-86eff500-6296-11e9-8c2d-d04cc08f5e41.png)

The fix I've been applying on my end after each update to Customizer has been to wrap the following lines in customizer.js:
https://github.com/creecros/Customizer/blob/master/Assets/js/customizer.js#L84-L164

With an if statement:
```
if (document.getElementById('loginpanel_color'))
{
        // Existing lines 84 - 164 should be in here now
}
```

Those lines cause the issue on the non-Customizer pages throughout Kanboard since they end up running no matter what, versus the other code in customizer.js being triggered on events/functions. Since those elements for the Customizer config don't exist in the other parts of Kanboard, they result in the errors being triggered since the elements don't exist so the if statement works around that by first checking for the existence of the loginpanel_color element and if it doesn't exist then everything in that if statement won't get run unnecessarily.

**Comment by creecros** [comment]
You want to take care of it and make a PR, or you want me to do it?

**Comment by orware** [comment]
Put together a quick PR for you.
