### ISSUE TITLE
Version 1.11.1 still reports 1.11.0 in Plugin.php

### ISSUE THREAD

**Issue by umasse** [creecros/Customizer#87]
Very simple issue: line 154, function getPluginVersion() still says 1.11.0.
Thanks for your hard work!

**Comment by creecros** [comment]
Thanks for noticing I actually remembered that last night and then fell asleep before I ever got a chance to fix it I'll take care of it next chance I get

**Comment by creecros** [comment]
There's also an intermittent issue I've noticed, not picking up the users ID from the user session, but it only happens to me once per day the first time I go to my test site, and then it never happen's again. So I'll probably just update 1.11.1 release files knowing 1.11.2 will be coming write behind it.

Problem is testing the intermittent issue, haven't figured out how to reliably reproduce when I need it to.

**Comment by umasse** [comment]
Sounds like one of those annoying issues that you can find in 5 minutes or in 5 months... Good luck!
I just edited the php file on my server, so no rush on my side.

**Comment by creecros** [comment]
updated the release for now:
https://github.com/creecros/Customizer/releases/tag/1.11.1
