### ISSUE TITLE
Login loop customizer

### ISSUE THREAD

**Issue by alvaradojao** [creecros/Customizer#88]
Hello Friends, Kanboard 1.2.9 Ubuntu 18 with customizer installed result in a login screen loop. Any ideas how to fixed?

**Comment by creecros** [comment]
Downgrade to 1.11.1 for now

**Comment by creecros** [comment]
Out of curiosity,  are you using an oauth?

**Comment by alvaradojao** [comment]
Ok, I am using LDAP authentication.
