### ISSUE TITLE
Board page is broken with Kanboard 1.2.10

### ISSUE THREAD

**Issue by ntimo** [creecros/Customizer#90]
Hello,
when I try to open the board page with the customizor plugin installed on Kanboard version 1.2.10 I simply get a blank screen. 

I have attached the log below:
[graylog-search-result-relative-172800.csv.zip](https://github.com/creecros/Customizer/files/3317542/graylog-search-result-relative-172800.csv.zip)

**Comment by creecros** [comment]
https://github.com/creecros/Customizer/blob/69a4e61b1879ffd329c0e2b4f8c1cf191ea68ebc/Plugin.php#L109

Something changed in 1.2.10, and the version compare now thinks 1.2.10 is less than 1.2.4, and its pulling the old pre 1.2.4 template. Can you confirm your version is reporting correct in your admin panel, "settings>about"

I'll take a look tonight. I just noticed the new KB version, so haven't had  the time to play with it.

**Comment by creecros** [comment]
that should fix it, let me know, just in case.

**Comment by ntimo** [comment]
Thank you very much 🙌🙌
