### ISSUE TITLE
Got an error message - missing userthemes

### ISSUE THREAD

**Issue by macksoneh** [creecros/Customizer#91]
Hi, I just installed the latest update and immediately got an error message.

Warning: scandir(plugins/Customizer/Assets/css/userthemes,plugins/Customizer/Assets/css/userthemes): The system cannot find the file specified. (code: 2) 
in C:\xxxxxxxx\kanboard\plugins\Customizer\Plugin.php on line 24
....
.....

Can you please look into this?
Thanks,
Mack

**Comment by macksoneh** [comment]
Hi, 
Additional information below;
I got the warning message when I installed the latest version 1.12.1.
Prior to installing the latest version, I uninstalled the previous version which was completed successfully.
Thanks,
Mack

**Comment by creecros** [comment]
Ah crap, I forgot the empty folder for userthemes... I'll fix it tonight.

**Comment by creecros** [comment]
I'm just gonna remake version 1.12.1, so just reinstall, i'll note it in the changelog for 1.12.1 as well.

**Comment by creecros** [comment]
it's all set: try reinstalling 1.12.1:
https://github.com/creecros/Customizer/releases/tag/1.12.1
