### ISSUE TITLE
Tag Text Colour off with Galaxy Theme

### ISSUE THREAD

**Issue by Ryonez** [creecros/Customizer#92]
The tag text colour is off for the galaxy theme.
Within a project:
![image](https://user-images.githubusercontent.com/16157130/60134969-d140a580-97f4-11e9-9ddc-20c06ff65dbf.png)
It is alright though when view from the dashboard:
![image](https://user-images.githubusercontent.com/16157130/60135009-e4ec0c00-97f4-11e9-9723-c749017dfe30.png)

**Comment by creecros** [comment]
Yuck. I suck at css, it shows huh?

**Comment by creecros** [comment]
@kenlog .boom{!}

**Comment by Ryonez** [comment]
Hey, it happens sometimes. No real big deal.

Oh, I've also asked him for a tweak, hehe.

**Comment by creecros** [comment]
Ya, we both are currently pouring our souls into a joint project, so we will get to it.

**Comment by Ryonez** [comment]
Okay, is this going to be fixed? I understand you're busy, but this should be a quick fix no?

**Comment by creecros** [comment]
Since you asked me twice, I'll try and do it tonight.

**Comment by creecros** [comment]
let me know if that was what you were looking for, or not.

**Comment by Ryonez** [comment]
Seems to have done the trick, thank you very much!
