### ISSUE TITLE
Custom login notice?

### ISSUE THREAD

**Issue by poVoq** [creecros/Customizer#94]
When using LDAP or generic Oauth2 it would be nice to be able to add a small text/HTML note to the login screen to explain to users with which account to login, or link to the external registration page.

Thanks.

**Comment by creecros** [comment]
Just add a custom note to login page? That's easy breezy. Next release.

**Comment by creecros** [comment]
How much control do you want over it? Font, size of note panel, etc...

![image](https://user-images.githubusercontent.com/26339368/64273558-8d160380-cf0f-11e9-9b74-cf7e27cda9e0.png)

**Comment by poVoq** [comment]
Hmm, for me something basic is sufficient. But it would be nice if it could include clickable links.

**Comment by creecros** [comment]
I believe you would be able to by using html in the note. Alternatively, I could use markdown, but in order to do that, I'd have to give the application roles to the method since no one is actually logged in yet when they are at the login screen.

**Comment by poVoq** [comment]
Sure, HTML links would be fine.

**Comment by creecros** [comment]
You can test it out here: https://projects.nachostudio.ml

admin/admin

html formatting works just fine inside the note. 

I still need to add to the live preview, and I have something else I want to improve before I make a new release. let me know if you have any more feedback on this though, before I finalize.

**Comment by poVoq** [comment]
Seems fine. Maybe by default have it at least as wide as the login box?

Thanks a lot for adding this!

**Comment by creecros** [comment]
https://github.com/creecros/Customizer/releases/tag/1.13.0

By default, the Note Panel will adjust to the size of the content. However, with HTML Formatting you could adjust the size of the panel to be larger than the content. 

Example: 
```
This is a test note.
And here is a test <a href="http:/test.com">link</a>.
<br>
I used a line break to go to second line.
<br>
<a style="color:red">And now I changed the color</a>
<div style="min-width:309px"></div>
```

![image](https://user-images.githubusercontent.com/26339368/64440010-2cb2cd80-d099-11e9-922d-63cca12c08f7.png)
