### ISSUE TITLE
Clicking on user tag on task shows broken modal-box

### ISSUE THREAD

**Issue by josch87** [creecros/Customizer#95]
### Actual behaviour
The modal box opens up and is not wide enough to fit all content. 

### Expected behaviour
The modal box should open up the same way as when clicking on "edit task" (action=edit). 

### Steps to reproduce
- Apply material theme
- Go to board or list view.
- Click on the round user sign on a task
- Modal box opens up

### Screenshots
When clicking edit task:
![2019-09-07_06h33_40](https://user-images.githubusercontent.com/33511915/64469840-76eb8b80-d139-11e9-92ba-3f4d2e22528d.png)

When clicking on user sign:
![2019-09-07_06h33_49](https://user-images.githubusercontent.com/33511915/64469841-76eb8b80-d139-11e9-993e-287a856f1a9c.png)

### Configuration

- Kanboard version: 1.2.11
- Database type and version: mysql 5.7.24
- PHP version: 7.1.31
- OS: Linux 3.16.0-7-amd64
- Browser: Chrome Version 76.0.3809.132 (Offizieller Build) (64-Bit), Firefox 69.0 (64-Bit)

**Comment by creecros** [comment]
I'll take a look, thanks for reporting.
