### ISSUE TITLE
Code background color in theme Galaxy

### ISSUE THREAD

**Issue by dankh** [creecros/Customizer#96]
In theme Galaxy code background color differs from markdown block background color. The result is code lines surrounded by the backgound color. It's very difficult to read.

Here is a small patch to fix it by applying the block background color : 

```
diff --git a/Assets/css/themes/Galaxy.css b/Assets/css/themes/Galaxy.css
index 9517cec..d8dfc1b 100644
--- a/Assets/css/themes/Galaxy.css
+++ b/Assets/css/themes/Galaxy.css
@@ -18,7 +18,7 @@ body {
        text-rendering:optimizeLegibility
 }
 code {
-       background-color: #cccccc52!important;
+       background-color: #242729 !important;
 }
 small {
        font-size:0.8em
```

## Before

![galaxy-background-color-before](https://user-images.githubusercontent.com/1543727/67850557-ee6de380-fb08-11e9-82c6-ff6b31bb5a7e.png)

## After

![galaxy-background-color-after](https://user-images.githubusercontent.com/1543727/67850574-f3329780-fb08-11e9-96b0-482d4acd9fef.png)

- Kanboard: v1.2.11
- Customizer: 1.13.1

Other installed plugins : 
 - HighlightCodeSyntax: 1.0.1

**Comment by creecros** [comment]
Make a pull request and I'll add it.

**Comment by creecros** [comment]
added:
 commit 35d0d5c267d86481fe30a32d34609a237007f594
