### ISSUE TITLE
Error after installing plugin

### ISSUE THREAD

**Issue by twsit988** [creecros/Customizer#97]
Hey, thanks so much for making this plugin. I'd really like to use it however I am getting an error after installing it. Please advise. TIA!

Warning: unlink(plugins/Customizer/Assets/css/userthemes/.gitignore): Permission denied in /var/www/kanboard/plugins/Customizer/Plugin.php on line 28

Warning: session_set_save_handler(): Cannot change save handler when headers already sent in /var/www/kanboard/app/Core/Session/SessionManager.php on line 41

Warning: session_set_cookie_params(): Cannot change session cookie parameters when headers already sent in /var/www/kanboard/app/Core/Session/SessionManager.php on line 92

Warning: ini_set(): Headers already sent. You cannot change the session module's ini settings at this time in /var/www/kanboard/app/Core/Session/SessionManager.php on line 96

Warning: ini_set(): Headers already sent. You cannot change the session module's ini settings at this time in /var/www/kanboard/app/Core/Session/SessionManager.php on line 97

Warning: ini_set(): Headers already sent. You cannot change the session module's ini settings at this time in /var/www/kanboard/app/Core/Session/SessionManager.php on line 100

Warning: session_name(): Cannot change session name when headers already sent in /var/www/kanboard/app/Core/Session/SessionManager.php on line 49

Warning: session_start(): Cannot start session when headers already sent in /var/www/kanboard/app/Core/Session/SessionManager.php on line 50

Warning: Cannot modify header information - headers already sent by (output started at /var/www/kanboard/plugins/Customizer/Plugin.php:28) in /var/www/kanboard/app/Core/Http/Response.php on line 222

Warning: Cannot modify header information - headers already sent by (output started at /var/www/kanboard/plugins/Customizer/Plugin.php:28) in /var/www/kanboard/app/Core/Http/Response.php on line 222

Warning: Cannot modify header information - headers already sent by (output started at /var/www/kanboard/plugins/Customizer/Plugin.php:28) in /var/www/kanboard/app/Core/Http/Response.php on line 222

Warning: Cannot modify header information - headers already sent by (output started at /var/www/kanboard/plugins/Customizer/Plugin.php:28) in /var/www/kanboard/app/Core/Http/Response.php on line 222

Warning: Cannot modify header information - headers already sent by (output started at /var/www/kanboard/plugins/Customizer/Plugin.php:28) in /var/www/kanboard/app/Core/Http/Response.php on line 222

Warning: Cannot modify header information - headers already sent by (output started at /var/www/kanboard/plugins/Customizer/Plugin.php:28) in /var/www/kanboard/app/Core/Http/Response.php on line 222

**Comment by creecros** [comment]
My first guess would be permissions to the plugin folder.

**Comment by twsit988** [comment]
The thing is this is the only plugin getting that error message. I have a whole bunch of other plugins in the same folder that are working fine.

**Comment by creecros** [comment]
It's the only plugin that's reading and writing in that folder. Is it not working at all, or your just getting an error message but its semi working?

**Comment by twsit988** [comment]
> It's the only plugin that's reading and writing in that folder. Is it not working at all, or your just getting an error message but its semi working? Try removing the .gitignore manually, see what happens.

Looks to be working now. May I ask how to move the login note up a little or all the way to the top? Or below the logo?

Right now the note exists far below the login button and you need to scroll down a lot to be able to see it.

**Comment by creecros** [comment]
Screenshot?

**Comment by twsit988** [comment]
> Screenshot?

See the spacing between login form and the login note text below?

![image](https://user-images.githubusercontent.com/56913340/68442532-41801e80-020c-11ea-9248-b44d6173d9f6.png)

**Comment by creecros** [comment]
I'm not seeing the div box around it, so im kindof confused. Can you screenshot the whole note for me and then see if you can replicate on my test server @ projects.nachostudio.ml
admin/admin

**Comment by twsit988** [comment]
Yours doesn't seem to have that much space between the login form and the note. Anyway, that's not my biggest concern.  Just wondering if it's possible to move things around and be able to customize it like a note in the header (below the logo) a note in the footer etc.

**Comment by creecros** [comment]
It's possible, but not unless you know the code. If I get time I'll try to add something.

**Comment by creecros** [comment]
Also, curious, what theme is yours?

**Comment by twsit988** [comment]
> Also, curious, what theme is yours?

I'm just using the default theme. This theme seems to look and work the best :)

**Comment by creecros** [comment]
I'm just trying to figure out what makes your setup appear different, I can tell by your screenshot, the font in particular, that something is different.

**Comment by twsit988** [comment]
It's the Greenwing plugin :)

It's not changing the spacing I was telling you about though because I tried deactivating the Greenwing plugin and the big gap/spacing is still there. Though that is not my concern, it'd be nice to have a more customizable login form :)

**Comment by creecros** [comment]
Greenwig plugin is most likely not compatible with Customizer, since it is more than just css, and it has a lot of overrides that may conflict. I have no intention of supporting other theme plugins, but it's possible that author could Customizer, may want to ask them.

The big gap spacing should not be there on a standard install, with no conflicts, i.e., I know it wont be there, I'm not guessing.

If I get time, I can add a hook to the top of the login screen, and give a choice, but would ask for separate feature request, since your error is resolved, I am closing this issue.

**Comment by djidji01** [comment]
> 
> 
> It's the only plugin that's reading and writing in that folder. Is it not working at all, or your just getting an error message but its semi working? Try removing the .gitignore manually, see what happens.

@creecros 
Think not really permission problem but when I downgrade my PHP version to 7.3 warnings go away!!

Incompatibility to php 7.4!!!

Thanks

**Comment by creecros** [comment]
@djidji01 #115
